name: CheckRun Timechart
description: Visualizes the performance of CheckRuns run a given SHA using an ASCII timechart
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'Github token for the repository'
    required: true
  SHA:
    description: The SHA to check
    required: false
  TRACE_START:
    description: The time from which to start the trace
    required: false
  DELAY:
    description: The amount of time to wait before querying the GitHub API.
    default: "5"
    required: false
  SUMMARY:
    description: Set to a truthy value to output the timechart to \$GITHUB_STEP_SUMMARY
    default: ""
    required: false
  DEBUG:
    description: set -x and BT_DEBUG
    default: ""
    required: false



runs:
  using: 'docker'
  image: 'Dockerfile'
