name: CheckRun Timechart
description: Visualizes the performance of CheckRuns run a given SHA using an ASCII timechart
branding:
  icon: 'activity'
  color: 'gray-dark'
inputs:
  GITHUB_TOKEN:
    description: 'Github token for the repository'
    required: true
  SHA:
    description: The SHA to check
    required: true
  TRACE_START:
    description: The time from which to start the trace
    required: true

runs:
  using: 'docker'
  image: 'docker://urcomputeringpal/checkrun-timechart-action:v0.0.5'
