name: pull_request
on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - closed
      - reopened
      - synchronize

jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: checkrun-timechart-github
        uses: ./
        timeout-minutes: 1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.event.pull_request.head.sha }}"
          TRACE_START: "${{ github.event.pull_request.updated_at }}"
          DEBUG: "true"
  summary:
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3
      - name: checkrun-timechart-github
        uses: ./
        timeout-minutes: 1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          SHA: "${{ github.event.pull_request.head.sha }}"
          TRACE_START: "${{ github.event.pull_request.updated_at }}"
          SUMMARY: "true"
          DEBUG: "true"
      