name: push
on:
  push:

jobs:
  slow_example:
    runs-on: ubuntu-latest
    steps:
      - run: echo things that take a second or two should show up
      - run: sleep 5

  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo duplicate job names should not cause failure

  push:
    runs-on: ubuntu-latest
    steps:
      - name: context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v3
      - name: checkrun-timechart-github
        timeout-minutes: 1
        uses: ./
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

